//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INTERSUR.INFSAP.WSConsulta.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://sepp.camargocorrea.com.br/sap/xi/engine?type=entry&version=3.0&Sender.Ser" +
            "vice=BS_TELECTRONICA&Interface=urn%3Acccc.telectronica.consulcompropagosap%5ESI_" +
            "ConsulComprPagoSapSyncOut")]
        public string INTERSUR_INFSAP_WSConsulta_WS_Consulta_SI_ConsulComprPagoSapSyncOutService {
            get {
                return ((string)(this["INTERSUR_INFSAP_WSConsulta_WS_Consulta_SI_ConsulComprPagoSapSyncOutService"]));
            }
        }
    }
}
